spring:
  application:
    name : Order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: 1234asdf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka